# Generated by Django 4.1.2 on 2022-11-05 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_product_size_alter_buyer_pic4_alter_product_pic1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Maincategory',
            new_name='maincategory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Subcategory',
            new_name='subcategory',
        ),
    ]
