# Generated by Django 4.1.2 on 2022-11-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_rename_brand_product_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Size',
            new_name='size',
        ),
    ]
