# Generated by Django 4.1.2 on 2022-11-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_rename_size_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='pic4',
            new_name='pic',
        ),
    ]
