# Generated by Django 4.1.2 on 2022-11-16 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_checkoutproducts_qty_checkoutproducts_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='data',
            new_name='date',
        ),
    ]
