# Generated by Django 4.1.2 on 2022-11-24 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_buyer_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='AddressLine1',
            new_name='addressline1',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='AddressLine2',
            new_name='addressline2',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='AddressLine3',
            new_name='addressline3',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='State',
            new_name='state',
        ),
    ]
